### ISSUE TITLE
(Feature request) Set specific color for executable files and links

### ISSUE THREAD

**Issue by Aeldit** [catppuccin/yazi#20]
Hi, so the idea would be to add the following 2 rules to the `[filetype]` part of the theme:
```toml
[filetype]
rules = [
  # ...
  { name = "*", is = "exec", fg = "#<color to define>" },
  { mime = "inode/*", is = "link", fg = "#<color to define>" },
]
```
to make them pop out when navigating through files 

Would this be possible?
